[workspace]

members = [
    "sandbox/counter",
    "sandbox/counter_next",
    "sandbox/bmi_calc",
    "sandbox/guessing_game",
    "sandbox/img_viewer",
    "sandbox/lang_ja",
    "sandbox/ttf_icon",
    "todo/calc",
]